name: simulacion
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - scipy
  - matplotlib
  - ipykernel
  - pathlib
  - seaborn
prefix: /home/dracdarktime/miniconda3/envs/simulacion
